name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Grab artifact
      uses: actions/upload-artifact@v4
      with:
        name: HexSigns-v{project.version}
        path: target/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: HexSigns-v{project.version}
        path: ./downloaded-artifacts

    - name: Create new release
      uses: softprops/action-gh-release@v2
      with:
        tag-name: v{{ project.version }}
        name: Alpha Release {{ github.run_number }}
        body: Automatically uploaded build from build {{ github.run_number }}
        draft: false
        prerelease: false
        files: ./downloaded-artifacts/*.jar
  
